// <auto-generated />
using System;
using DocAnalytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocAnalytics.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocAnalytics.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("NewState")
                        .HasColumnType("text")
                        .HasColumnName("new_state");

                    b.Property<string>("OldState")
                        .HasColumnType("text")
                        .HasColumnName("old_state");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_activity_log");

                    b.HasIndex("TenantId", "SiteId", "CreatedAt")
                        .HasDatabaseName("ix_activity_log_tenant_id_site_id_created_at");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_document_types");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("ix_document_types_type_name");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.ErrorCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("RemediationMsg")
                        .HasColumnType("text")
                        .HasColumnName("remediation_msg");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_error_catalog");

                    b.HasIndex("ErrorCode")
                        .IsUnique()
                        .HasDatabaseName("ix_error_catalog_error_code");

                    b.ToTable("error_catalog", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.FileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_step");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("extraction_confidence");

                    b.Property<string>("ExtractionStatus")
                        .HasColumnType("text")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_files_document_type_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_files_transaction_id");

                    b.HasIndex("TenantId", "SiteId", "DocumentTypeId")
                        .HasDatabaseName("ix_files_tenant_id_site_id_document_type_id");

                    b.HasIndex("TenantId", "SiteId", "Status", "LastUpdatedAt")
                        .HasDatabaseName("ix_files_tenant_id_site_id_status_last_updated_at");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.FileStepHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_name");

                    b.HasKey("Id")
                        .HasName("pk_file_step_history");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_file_step_history_document_type_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_step_history_file_id");

                    b.HasIndex("StepName", "Status")
                        .HasDatabaseName("ix_file_step_history_step_name_status");

                    b.ToTable("file_step_history", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<Guid?>("ItemCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_category_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoice_line_items");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_invoice_line_items_file_id");

                    b.HasIndex("ItemCategoryId")
                        .HasDatabaseName("ix_invoice_line_items_item_category_id");

                    b.HasIndex("TenantId", "SiteId", "ItemCategoryId")
                        .HasDatabaseName("ix_invoice_line_items_tenant_id_site_id_item_category_id");

                    b.ToTable("invoice_line_items", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_item_categories");

                    b.HasIndex("CategoryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_item_categories_category_code");

                    b.ToTable("item_categories", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sites_tenant_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("ProcessingCount")
                        .HasColumnType("integer")
                        .HasColumnName("processing_count");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.Property<int>("UploadedCount")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_count");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("TenantId", "SiteId", "LastUpdatedAt")
                        .HasDatabaseName("ix_transactions_tenant_id_site_id_last_updated_at");

                    b.HasIndex("TenantId", "SiteId", "State")
                        .HasDatabaseName("ix_transactions_tenant_id_site_id_state");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.UserSiteAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_site_access");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_user_site_access_site_id");

                    b.HasIndex("UserId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_site_access_user_id_site_id");

                    b.ToTable("user_site_access", (string)null);
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.FileRecord", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("fk_files_document_types_document_type_id");

                    b.HasOne("DocAnalytics.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Files")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_transactions_transaction_id");

                    b.Navigation("DocumentType");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.FileStepHistory", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("fk_file_step_history_document_types_document_type_id");

                    b.HasOne("DocAnalytics.Domain.Entities.FileRecord", "File")
                        .WithMany("Steps")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_step_history_files_file_id");

                    b.Navigation("DocumentType");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.FileRecord", "File")
                        .WithMany("LineItems")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_line_items_files_file_id");

                    b.HasOne("DocAnalytics.Domain.Entities.ItemCategory", "ItemCategory")
                        .WithMany("LineItems")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invoice_line_items_item_categories_item_category_id");

                    b.Navigation("File");

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Site", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Sites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sites_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.User", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.UserSiteAccess", b =>
                {
                    b.HasOne("DocAnalytics.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_site_access_sites_site_id");

                    b.HasOne("DocAnalytics.Domain.Entities.User", "User")
                        .WithMany("SiteAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_site_access_users_user_id");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.FileRecord", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.ItemCategory", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("DocAnalytics.Domain.Entities.User", b =>
                {
                    b.Navigation("SiteAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
